### ISSUE TITLE
can not build with 6.17 kernel if CONFIG_DEV_DAX_PMEM is enabled

### ISSUE THREAD

**Issue by AndrewV666** [LINBIT/drbd#124]
After https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=21aa65bf82a78c1e70447a45a85e533689b7f1a7
(mm: remove callers of pfn_t functionality) there is no linux/pfn_t.h header file,
so drbd/drbd_dax_pmem.c can not compile due to "#include <linux/pfn_t.h>" line.

**Comment by delgado23** [comment]
I seem to be running into this same issue on Proxmox 9.0.X trying to upgrade to kernel 6.17.

```
root@pve-03:~# apt install proxmox-kernel-6.17 proxmox-headers-6.17.1-1-pve
Installing:                     
  proxmox-headers-6.17.1-1-pve  proxmox-kernel-6.17

Installing dependencies:
  proxmox-kernel-6.17.1-1-pve-signed

Summary:
  Upgrading: 0, Installing: 3, Removing: 0, Not Upgrading: 0
  Download size: 140 MB
  Space needed: 1,094 MB / 57.1 GB available

Continue? [Y/n] y
Get:1 http://download.proxmox.com/debian/pve trixie/pve-no-subscription amd64 proxmox-headers-6.17.1-1-pve amd64 6.17.1-1 [15.3 MB]
Get:2 http://download.proxmox.com/debian/pve trixie/pve-no-subscription amd64 proxmox-kernel-6.17.1-1-pve-signed amd64 6.17.1-1 [124 MB]
Get:3 http://download.proxmox.com/debian/pve trixie/pve-no-subscription amd64 proxmox-kernel-6.17 all 6.17.1-1 [11.4 kB]                                                                     
Fetched 140 MB in 21s (6,613 kB/s)                                                                                                                                                           
Selecting previously unselected package proxmox-headers-6.17.1-1-pve.
(Reading database ... 176647 files and directories currently installed.)
Preparing to unpack .../proxmox-headers-6.17.1-1-pve_6.17.1-1_amd64.deb ...
Unpacking proxmox-headers-6.17.1-1-pve (6.17.1-1) ...
Selecting previously unselected package proxmox-kernel-6.17.1-1-pve-signed.
Preparing to unpack .../proxmox-kernel-6.17.1-1-pve-signed_6.17.1-1_amd64.deb ...
Unpacking proxmox-kernel-6.17.1-1-pve-signed (6.17.1-1) ...
Selecting previously unselected package proxmox-kernel-6.17.
Preparing to unpack .../proxmox-kernel-6.17_6.17.1-1_all.deb ...
Unpacking proxmox-kernel-6.17 (6.17.1-1) ...
Setting up proxmox-headers-6.17.1-1-pve (6.17.1-1) ...
Setting up proxmox-kernel-6.17.1-1-pve-signed (6.17.1-1) ...
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/dkms 6.17.1-1-pve /boot/vmlinuz-6.17.1-1-pve
Sign command: /lib/modules/6.17.1-1-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Autoinstall of module drbd/9.2.15-1 for kernel 6.17.1-1-pve (x86_64)
Building module(s)......(bad exit status: 2)
Failed command:
make -j20 KERNELRELEASE=6.17.1-1-pve -C src/drbd KDIR=/lib/modules/6.17.1-1-pve/build

Error! Bad return status for module build on kernel: 6.17.1-1-pve (x86_64)
Consult /var/lib/dkms/drbd/9.2.15-1/build/make.log for more information.

Autoinstall on 6.17.1-1-pve failed for module(s) drbd(10).

Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
run-parts: /etc/kernel/postinst.d/dkms exited with return code 1
Failed to process /etc/kernel/postinst.d at /var/lib/dpkg/info/proxmox-kernel-6.17.1-1-pve-signed.postinst line 20.
dpkg: error processing package proxmox-kernel-6.17.1-1-pve-signed (--configure):
 installed proxmox-kernel-6.17.1-1-pve-signed package post-installation script subprocess returned error exit status 2
dpkg: dependency problems prevent configuration of proxmox-kernel-6.17:
 proxmox-kernel-6.17 depends on proxmox-kernel-6.17.1-1-pve-signed | proxmox-kernel-6.17.1-1-pve; however:
  Package proxmox-kernel-6.17.1-1-pve-signed is not configured yet.
  Package proxmox-kernel-6.17.1-1-pve is not installed.
  Package proxmox-kernel-6.17.1-1-pve-signed which provides proxmox-kernel-6.17.1-1-pve is not configured yet.

dpkg: error processing package proxmox-kernel-6.17 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 proxmox-kernel-6.17.1-1-pve-signed
 proxmox-kernel-6.17
Error: Sub-process /usr/bin/dpkg returned an error code (1)

```

```
/var/lib/dkms/drbd/9.2.15-1/build/src/drbd/drbd_dax_pmem.c:25:10: fatal error: linux/pfn_t.h: No such file or directory
   25 | #include <linux/pfn_t.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.17.1-1-pve/scripts/Makefile.build:287: drbd_dax_pmem.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-headers-6.17.1-1-pve/Makefile:2016: .] Error 2
make[1]: *** [Makefile:248: __sub-make] Error 2
make: *** [Makefile:248: kbuild] Error 2
make: Leaving directory '/var/lib/dkms/drbd/9.2.15-1/build/src/drbd'

# exit code: 2
# elapsed time: 00:00:11
```
