### ISSUE TITLE
The new kernel version compilation problem

### ISSUE THREAD

**Issue by twtlpla** [LINBIT/drbd#87]
hi，
     When compiling drbd version 9.2.7 based on the newer kernel version, the following error occurs. After investigation, because the newer version of the kernel will be used by drbd to cut several functions, resulting in compilation failure. It is estimated that future versions of the kernel will not restore these functions. What is the solution to this situation? Is there a plan to adapt the latest kernel version?
    New versions of kernel functions are available for reference：https://github.com/torvalds/linux/blob/master/block/bdev.c
          
          /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_receiver.c: In function ‘convert_state’中:
          /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_receiver.c:6514:27: warning：implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
           6514 |                 [L_OFF] = L_OFF,
                |                           ^~~~~
          /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_receiver.c:6515:35: warning：implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
           6515 |                 [L_ESTABLISHED] = L_ESTABLISHED,
                |                                   ^~~~~~~~~~~~~
          /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_receiver.c:6517:39: warning：implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
           6517 |                 [L_STARTING_SYNC_S] = L_STARTING_SYNC_T,
                |                                       ^~~~~~~~~~~~~~~~~
          /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_receiver.c:6518:39: warning：implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
           6518 |                 [L_STARTING_SYNC_T] = L_STARTING_SYNC_S,
                |                                       ^~~~~~~~~~~~~~~~~
          /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_receiver.c:6519:35: warning：implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
           6519 |                 [L_WF_BITMAP_S] = L_WF_BITMAP_T,
                |                                   ^~~~~~~~~~~~~
          /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_receiver.c:6520:35: warning：implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
           6520 |                 [L_WF_BITMAP_T] = L_WF_BITMAP_S,
                |                                   ^~~~~~~~~~~~~
          /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_receiver.c:6523:38: warning：implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
           6523 |                 [L_VERIFY_S]       = L_VERIFY_T,

          CC [M]  /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_req.o
          CC [M]  /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_actlog.o
          CC [M]  /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_main.o
          CC [M]  /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_strings.o
          CC [M]  /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.o
        /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.c:In fuction‘close_backing_dev’:
        /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.c:2607:9: error：implicit declaration of function ‘blkdev_put’; did you mean ‘dev_put’? [-Werror=implicit-function-declaration]
         2607 |         blkdev_put(bdev, FMODE_READ | FMODE_WRITE | FMODE_EXCL);
              |         ^~~~~~~~~~
              |         dev_put
        /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.c:2607:53: error：‘FMODE_EXCL’ undeclared (first use in this function); did you mean ‘FMODE_EXEC’?
         2607 |         blkdev_put(bdev, FMODE_READ | FMODE_WRITE | FMODE_EXCL);
              |                                                     ^~~~~~~~~~
              |                                                     FMODE_EXEC
        /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.c:2607:53: note:  each undeclared identifier is reported only once for each function it appears in
        /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.c: In function ‘open_backing_dev’:
        /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.c:2629:37: error：implicit declaration of function ‘blkdev_get_by_path’; did you mean ‘bdev_open_by_path’? [-Werror=implicit-function-declaration]
         2629 |         struct block_device *bdev = blkdev_get_by_path(bdev_path,
              |                                     ^~~~~~~~~~~~~~~~~~
              |                                     bdev_open_by_path
        /root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.c:2630:62: error：‘FMODE_EXCL’ undeclared (first use in this function); did you mean ‘FMODE_EXEC’?
         2630 |                                   FMODE_READ | FMODE_WRITE | FMODE_EXCL,
              |                                                              ^~~~~~~~~~
              |                                                              FMODE_EXEC
        cc1：some warnings being treated as errors
        make[3]: *** [scripts/Makefile.build:243：/root/rpmbuild/SOURCES/drbd-9.2.7/drbd/drbd_nl.o] error 1
        make[2]: *** [Makefile:1922：/root/rpmbuild/SOURCES/drbd-9.2.7/drbd] error 2
        make[1]: *** [Makefile:184：kbuild] error 2
        make: *** [Makefile:126：module] error 2

thanks

**Comment by chrboe** [comment]
We updated the kernel compat in fcd69c13a97ccce485f9a2172fa2d84026d5e407 (and fixed it up in cdd3b8aa03f1a58d71398275bb0d4bc13ad1eedc), so the latest master/drbd-9.1 from git should build with kernels up to 6.8.

**Comment by cirruspl** [comment]
Compilation errors in Proxmox (8.2.2 with proxmox-kernel-6.8.4-2-pve-signed) persist 
```
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_main.c:2897:6: warning: no previous prototype for ‘drbd_fsync_device’ [-Wmissing-prototypes]
 2897 | void drbd_fsync_device(struct drbd_device *device)
      |      ^~~~~~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c: In function ‘close_backing_dev’:
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2719:9: error: implicit declaration of function ‘blkdev_put’; did you mean ‘dev_put’? [-Werror=implicit-function-declaration]
 2719 |         blkdev_put(bdev, FMODE_READ | FMODE_WRITE | FMODE_EXCL);
      |         ^~~~~~~~~~
      |         dev_put
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2719:53: error: ‘FMODE_EXCL’ undeclared (first use in this function); did you mean ‘FMODE_EXEC’?
 2719 |         blkdev_put(bdev, FMODE_READ | FMODE_WRITE | FMODE_EXCL);
      |                                                     ^~~~~~~~~~
      |                                                     FMODE_EXEC
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2719:53: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c: In function ‘open_backing_dev’:
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2741:37: error: implicit declaration of function ‘blkdev_get_by_path’; did you mean ‘bdev_open_by_path’? [-Werror=implicit-function-declaration]
 2741 |         struct block_device *bdev = blkdev_get_by_path(bdev_path,
      |                                     ^~~~~~~~~~~~~~~~~~
      |                                     bdev_open_by_path
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2742:62: error: ‘FMODE_EXCL’ undeclared (first use in this function); did you mean ‘FMODE_EXEC’?
 2742 |                                   FMODE_READ | FMODE_WRITE | FMODE_EXCL,
      |                                                              ^~~~~~~~~~
      |                                                              FMODE_EXEC
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c: At top level:
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:3075:5: warning: no previous prototype for ‘drbd_md_read’ [-Wmissing-prototypes]
 3075 | int drbd_md_read(struct drbd_config_context *adm_ctx, struct drbd_backing_dev *bdev)
      |     ^~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:6652:5: warning: no previous prototype for ‘param_set_drbd_strict_names’ [-Wmissing-prototypes]
 6652 | int param_set_drbd_strict_names(const char *val, const struct kernel_param *kp)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:7328:5: warning: no previous prototype for ‘notify_path_state’ [-Wmissing-prototypes]
 7328 | int notify_path_state(struct sk_buff *skb,
      |     ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:243: /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.o] Błąd 1
make[2]: *** Oczekiwanie na niezakończone zadania....
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c: In function ‘convert_state’:
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6568:27: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6568 |                 [L_OFF] = L_OFF,
      |                           ^~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6569:35: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6569 |                 [L_ESTABLISHED] = L_ESTABLISHED,
      |                                   ^~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6571:39: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6571 |                 [L_STARTING_SYNC_S] = L_STARTING_SYNC_T,
      |                                       ^~~~~~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6572:39: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6572 |                 [L_STARTING_SYNC_T] = L_STARTING_SYNC_S,
      |                                       ^~~~~~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6573:35: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6573 |                 [L_WF_BITMAP_S] = L_WF_BITMAP_T,
      |                                   ^~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6574:35: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6574 |                 [L_WF_BITMAP_T] = L_WF_BITMAP_S,
      |                                   ^~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6577:38: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6577 |                 [L_VERIFY_S]       = L_VERIFY_T,
      |                                      ^~~~~~~~~~
```
